version: '3'

services:
  # Контейнер для вашего микросервиса
  todo-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017
    networks:
      - todo-network

  # Контейнер для базы данных MongoDB
  mongo:
    image: mongo:4.4.23-focal
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - todo-network

networks:
  todo-network:

volumes:
  mongodb-data:
